### ISSUE TITLE
Error in 2.8

### ISSUE THREAD

**Issue by Tazshelby2016** [leafar-tb/proc-fruits#2]
```
Traceback (most recent call last):
  File "█", line 259, in execute
    blObj = newEvObj.toMeshObject()
  File "█", line 48, in toMeshObject
    newMesh = self.toMesh(*args, **kwargs)
  File "█", line 285, in toMesh
    mm.add(*curvedScrew(self._outerSpline(), self._spine(), LODr=LOD, LODp=max(LOD, self.grooves*4*max(2, int(self.groovepower))), rScale=self._grooveFunction),
  File "█", line 340, in curvedScrew
    verts.append( rScale(angle) * ( surfPoint.x*bases[i][1] + surfPoint.y*bases[i][2] ) )
  File "█", line 274, in _grooveFunction
    return ( .5 - (abs(s))**fib(self.groovepower) ) * self.grooveDepth + 1
  File "█", line 271, in fib
    return (1-frac)*arr[n] + frac*arr[n+1]
IndexError: list index out of range

location: <unknown location>:-1
```

**Comment by leafar-tb** [comment]
Finally found some time and motivation to look into this. I fixed some issues and it should work fine again.

**Comment by Tazshelby2016** [comment]
Works good.
