### ISSUE TITLE
Operators are not accessible

### ISSUE THREAD

**Issue by Tazshelby2016** [leafar-tb/proc-fruits#3]
When you search after pressing space, the operators do not show up. No other access methods seem to exist, making the add-on unreachable.

**Comment by Tazshelby2016** [comment]
It now appears in the search menu once and the edit menu twice.
I get the following error, however:

```python
Python: Traceback (most recent call last):
  File "██\proc-fruits\evolution.py", line 246, in execute
    blObj = newEvObj.toMeshObject()
  File "██\proc-fruits\evolution.py", line 48, in toMeshObject
    newMesh = self.toMesh(*args, **kwargs)
  File "██\proc-fruits\fruit.py", line 293, in toMesh
    mm.add(*curvedScrew(self._outerSpline(), self._spine(), LODr=LOD, LODp=max(LOD, self.grooves*4*max(2, int(self.groovepower))), rScale=self._grooveFunction),
  File "██\proc-fruits\fruit.py", line 216, in _outerSpline
    x = 0, self.length*self.girdlePosition, self.length
AttributeError: 'Fruit' object has no attribute 'length'

location: <unknown location>:-1
```

**Comment by leafar-tb** [comment]
I found the duplication issue, but the other error I still need to figure out

**Comment by leafar-tb** [comment]
should be working again
